site_name: Scared's Mods & Plugins | Wiki
site_url: https://scaredrabbitnl.github.io/wiki/
nav: 
- Home: 
    - Welcome: 'index.md'
    - Mods: 'mods/index.md'
    - Plugins: 'plugins/index.md'
    - Credits: 'credits.md'
- Mods:
    - 'mods/index.md'
    - Reworked Netherite:
      - About the mod: 'mods/reworked-netherite/index.md'
      - Blocks: 'mods/reworked-netherite/blocks/index.md'
      - Items: 'mods/reworked-netherite/items/index.md'
      - Enchantments: 'mods/reworked-netherite/enchantments/index.md'
      - Fluids: 'mods/reworked-netherite/fluids/index.md'
    - More Outputs API: 
      - Getting Started: 'mods/more-outputs-api/index.md'
      - Extra information: 'mods/more-outputs-api/extra-info.md'
      - Block: 'mods/more-outputs-api/block.md'
      - Block Entity: 
          - 'mods/more-outputs-api/block-entity/index.md'
          - Two Outputs: 'mods/more-outputs-api/block-entity/two-outputs/index.md'
          - Three Outputs: 'mods/more-outputs-api/block-entity/three-outputs/index.md'
          - Four Outputs: 'mods/more-outputs-api/block-entity/four-outputs/index.md'
      - Recipes: 
          - Making a custom recipe: 'mods/more-outputs-api/recipe/index.md'
          - Two output recipe: 'mods/more-outputs-api/recipe/two-output-recipe/index.md'
          - Three output recipe: 'mods/more-outputs-api/recipe/three-output-recipe/index.md'
          - Four output recipe: 'mods/more-outputs-api/recipe/four-output-recipe/index.md'
      - Screenhandlers: 
          - Getting started with screenhandlers: 'mods/more-outputs-api/screen/index.md'
          - Example screen handler: 'mods/more-outputs-api/screen/examplescreenhandler.md'
          - Example screen: 'mods/more-outputs-api/screen/examplescreen.md'
          
      - Finishing up:
          - Registering: 'mods/more-outputs-api/registering.md'
          - Connecting screen: 'mods/more-outputs-api/connecting.md'
          - Other things: 'mods/more-outputs-api/other-things.md'
- Plugins: 
    - 'plugins/index.md'
    - SubCommandLib: 
      - Getting Started: 'plugins/subcommandlib/index.md'
      - Manager class: 'plugins/subcommandlib/manager.md'
      - Adding Subcommands: 'plugins/subcommandlib/subcommands.md'
      - Registering: 'plugins/subcommandlib/registering.md'
- Version Schemes: 
    - 'version-schemes/index.md'
    - Mod version schemes: 'version-schemes/mod.md'
    - Plugin version schemes: 'version-schemes/plugin.md'

repo_name: scaredrabbitnl/wiki/
repo_url: https://github.com/ScaredRabbitNL/wiki/



theme: 
  name: material
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle

  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@scaredrabbitnl
    - icon: simple/modrinth
      link: https://modrinth.com/user/scaredrabbitnl_
    - icon: simple/curseforge
      link: https://www.curseforge.com/members/scaredrabbitnl/projects
plugins:
  - tags
  
